### ISSUE TITLE
希望支持更多日记格式，2.11.1后的思源日记有属性，可以直接查询

### ISSUE THREAD

**Issue by mozhux** [suka233/siyuan-knote#1]
如题，我的日记格式是这样，不是标准的年月日，省略了，目前插件设置笔记本后提示没有找到对应的日记。
![image](https://github.com/suka233/siyuan-knote/assets/46953371/729269a8-af17-4628-9ed3-7a5a6e8b7f2c)
新版思源，可以根据日记属性来查找了！可以通用适配大量不同的格式了应该。建议支持一下
https://ld246.com/article/1701761466782

**Comment by suka233** [comment]
感谢告知，KNote新版已经新增了实验性的查询功能，但是由于我的日记并非其它格式，所以可能测试不出来什么bug，有任何问题请反馈

**Comment by uulaile** [comment]
黑夜模式下，面板打开，里面什么也看不清楚哦
![image](https://github.com/suka233/siyuan-knote/assets/96331996/232c02f6-a5d7-4744-9684-9b8752f11a2f)
