### ISSUE TITLE
在Dailynote中新的记录添加至页面最前端

### ISSUE THREAD

**Issue by 5kyfkr** [suka233/siyuan-knote#10]
如题，现在添加记录的顺序是在页面后端插入，但是我在Dailynote中会使用到标题块写文章，如果插入到标题块后方就会进入文章的范围内了，所以需要能插入到日记页面最前端，希望能支持切换添加位置，感谢作者开发如此好用的插件

**Comment by suka233** [comment]
可能是个比较常见的需求，但是这个插件做的话挺麻烦的，或许可以向D提个接口需求，这样的话各个插件作者都能获益，不用重复造轮子。
类似于 /api/block/appendDailyNoteBlock 这个接口是给日记的末尾添加块；新增一个给日记的开头添加块的接口就好了。

**Comment by 5kyfkr** [comment]
> 可能是个比较常见的需求，但是这个插件做的话挺麻烦的，或许可以向D提个接口需求，这样的话各个插件作者都能获益，不用重复造轮子。 类似于 /api/block/appendDailyNoteBlock 这个接口是给日记的末尾添加块；新增一个给日记的开头添加块的接口就好了。

我用memos同步插件的时候，memos有新的记录，类似微博时间线，是往笔记页面最前端插入的，他那个是不是原理不一样
![image](https://github.com/suka233/siyuan-knote/assets/63196026/a0a28a22-97d1-4afc-bb81-203e39dd38ed)

**Comment by suka233** [comment]
> > 可能是个比较常见的需求，但是这个插件做的话挺麻烦的，或许可以向D提个接口需求，这样的话各个插件作者都能获益，不用重复造轮子。 类似于 /api/block/appendDailyNoteBlock 这个接口是给日记的末尾添加块；新增一个给日记的开头添加块的接口就好了。
> 
> 我用memos同步插件的时候，memos有新的记录，类似微博时间线，是往笔记页面最前端插入的，他那个是不是原理不一样

实现应该是能实现的，只是不太想重复造轮子~。~

**Comment by 5kyfkr** [comment]
> > > 可能是个比较常见的需求，但是这个插件做的话挺麻烦的，或许可以向D提个接口需求，这样的话各个插件作者都能获益，不用重复造轮子。 类似于 /api/block/appendDailyNoteBlock 这个接口是给日记的末尾添加块；新增一个给日记的开头添加块的接口就好了。
> > 
> > 
> > 我用memos同步插件的时候，memos有新的记录，类似微博时间线，是往笔记页面最前端插入的，他那个是不是原理不一样
> 
> 实现应该是能实现的，只是不太想重复造轮子~。~

能不能参考下memos的看看，都是开源的吧

**Comment by 5kyfkr** [comment]
> 可能是个比较常见的需求，但是这个插件做的话挺麻烦的，或许可以向D提个接口需求，这样的话各个插件作者都能获益，不用重复造轮子。 类似于 /api/block/appendDailyNoteBlock 这个接口是给日记的末尾添加块；新增一个给日记的开头添加块的接口就好了。

@88250  
D大，有没有可能增加个接口在日记前端插入块？

**Comment by 5kyfkr** [comment]
还有大佬，这个快捷键issue有没可能修复下https://github.com/frostime/sy-docs-flow/issues/57 ，添加到数据库和制卡这两个快捷键还是挺常用的，当然没有也问题不大，快速输入后一天结束再对应添加或制卡

**Comment by suka233** [comment]
> 还有大佬，这个快捷键issue有没可能修复下[frostime/sy-docs-flow#57](https://github.com/frostime/sy-docs-flow/issues/57) ，添加到数据库和制卡这两个快捷键还是挺常用的，当然没有也问题不大，快速输入后一天结束再对应添加或制卡

这个会在我之后推出knote便利贴模式的时候看一下，当前版本暂时不动。因为便利贴我会考虑设计成渲染多个编辑器，可能会遇到f佬说的问题：
https://github.com/frostime/sy-docs-flow/issues/57#issuecomment-2081357124

为了避免踩坑，就先等等啦

**Comment by 5kyfkr** [comment]
> > 还有大佬，这个快捷键issue有没可能修复下[frostime/sy-docs-flow#57](https://github.com/frostime/sy-docs-flow/issues/57) ，添加到数据库和制卡这两个快捷键还是挺常用的，当然没有也问题不大，快速输入后一天结束再对应添加或制卡
> 
> 这个会在我之后推出knote便利贴模式的时候看一下，当前版本暂时不动。因为便利贴我会考虑设计成渲染多个编辑器，可能会遇到f佬说的问题： [frostime/sy-docs-flow#57 (comment)](https://github.com/frostime/sy-docs-flow/issues/57#issuecomment-2081357124)
> 
> 为了避免踩坑，就现等等啦

可以滴，那就先等等，现在主要还是能从前往后插入新块比较需要，现在我的DN用法是这样的https://ld246.com/article/1713942568107

**Comment by 88250** [comment]
> > 可能是个比较常见的需求，但是这个插件做的话挺麻烦的，或许可以向D提个接口需求，这样的话各个插件作者都能获益，不用重复造轮子。 类似于 /api/block/appendDailyNoteBlock 这个接口是给日记的末尾添加块；新增一个给日记的开头添加块的接口就好了。
> 
> @88250 D大，有没有可能增加个接口在日记前端插入块？

请关注 https://github.com/siyuan-note/siyuan/issues/11442

**Comment by 5kyfkr** [comment]
@suka233 大佬思源发dev版了，可以测试下能不能加进去了

**Comment by suka233** [comment]
done

**Comment by 5kyfkr** [comment]
> done

感谢大佬，大赞
