### ISSUE TITLE
无法对过去日期新建日记

### ISSUE THREAD

**Issue by 2zzw** [suka233/siyuan-knote#13]
如图我在 11 月 3 日时，点击到 11 月 2 日新建输入文字并回车后，日记被保存到 3 号而不是我新建的 2 号
（还有一个小问题：这个菜单头确实不怎么好看😅）
<img width="574" alt="image" src="https://github.com/user-attachments/assets/37fe5940-cb83-487d-b815-189fa59d0d56">

**Comment by 2zzw** [comment]
https://github.com/user-attachments/assets/d9a3b271-e210-407d-83fd-c74658423b12

**Comment by suka233** [comment]
hello你好  knote设计就是如此  只用于当天的记录  如果要在其他日期记录 使用/菜单就行
