### ISSUE TITLE
异常卡顿，关闭此插件后，内存占用率下降

### ISSUE THREAD

**Issue by lvzhp** [suka233/siyuan-knote#2]
![42a04c708a59243fd3fbaba1bdcabc7d](https://github.com/suka233/siyuan-knote/assets/71172482/365772b9-9f61-4f51-89e6-121062b67c11)

**Comment by suka233** [comment]
你好，请问一下是因为有很多callout吗？如果可能是的话，请粗略的估算一下大概有多少callout

**Comment by lvzhp** [comment]
> 你好，请问一下是因为有很多callout吗？如果可能是的话，请粗略的估算一下大概有多少callout

笔记里面没有callout

**Comment by suka233** [comment]
> > 你好，请问一下是因为有很多callout吗？如果可能是的话，请粗略的估算一下大概有多少callout
> 
> 笔记里面没有callout

可以的话，请按以下步骤操作一下：
首先将思源和knote升级到新版
关闭所有的插件和主题，只使用官方主题和knote，看下是否还卡顿；
如果不卡顿了，可以尝试一个一个开启的主题和插件，每开一个，观察以下内存情况，找出是什么插件冲突了；

顺便请说下你的思源版本和系统版本和knote版本

**Comment by suka233** [comment]
hello 最新版基本已经解决了卡顿的问题  请更新到最新版试试

**Comment by lvzhp** [comment]
此BUG，目前来看，依然存在。

当前已处于思源版本最新，插件版本最新。
![image](https://github.com/suka233/siyuan-knote/assets/71172482/99eef35b-a42a-4791-9971-03746623b232)
上图为开启插件状态。
![image](https://github.com/suka233/siyuan-knote/assets/71172482/edf980df-c4bb-4bfa-bc50-4623e5445a29)
上图为关闭插件状态。

打开 的笔记 中callout数量为5个。

**Comment by lvzhp** [comment]
系统为：win11

**Comment by suka233** [comment]
> 此BUG，目前来看，依然存在。
> 
> 当前已处于思源版本最新，插件版本最新。 ![image](https://private-user-images.githubusercontent.com/71172482/297129896-99eef35b-a42a-4791-9971-03746623b232.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjAxNjgsIm5iZiI6MTcwNTQ1OTg2OCwicGF0aCI6Ii83MTE3MjQ4Mi8yOTcxMjk4OTYtOTllZWYzNWItYTQyYS00NzkxLTk5NzEtMDM3NDY2MjNiMjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAyNTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYTk3MGYzNWJkNWRlZWUwNWM5ZmEzMWVmYWQ5NjZmY2JjOTRjYTA2NzZhMTM1ZWNhYWRiM2QzMDQwYjM2MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1sOFtddSEuW382oPphE95XXYJZJ_gqoTeBlknKdeOR0) 上图为开启插件状态。 ![image](https://private-user-images.githubusercontent.com/71172482/297130128-edf980df-c4bb-4bfa-bc50-4623e5445a29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjAxNjgsIm5iZiI6MTcwNTQ1OTg2OCwicGF0aCI6Ii83MTE3MjQ4Mi8yOTcxMzAxMjgtZWRmOTgwZGYtYzRiYi00YmZhLWJjNTAtNDYyM2U1NDQ1YTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAyNTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOGY4ZmU1YzQyZWVkNjNlMjMyOWM4NzlhYWMyZjdhNWEzNzQyYzlhNGVhMDQyMjVlOGI5NzMzNjQ2YmJjODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E_YLNwmFVMgHAii439eIlyFA7B4CbSxEb8IFCbxtYfE) 上图为关闭插件状态。
> 
> 打开 的笔记 中callout数量为5个。


请试试 关闭所有的插件和主题，只使用官方主题和knote，看下是否还卡顿；

**Comment by lvzhp** [comment]
> > 此BUG，目前来看，依然存在。
> > 当前已处于思源版本最新，插件版本最新。 ![image](https://private-user-images.githubusercontent.com/71172482/297129896-99eef35b-a42a-4791-9971-03746623b232.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjAxNjgsIm5iZiI6MTcwNTQ1OTg2OCwicGF0aCI6Ii83MTE3MjQ4Mi8yOTcxMjk4OTYtOTllZWYzNWItYTQyYS00NzkxLTk5NzEtMDM3NDY2MjNiMjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAyNTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYTk3MGYzNWJkNWRlZWUwNWM5ZmEzMWVmYWQ5NjZmY2JjOTRjYTA2NzZhMTM1ZWNhYWRiM2QzMDQwYjM2MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1sOFtddSEuW382oPphE95XXYJZJ_gqoTeBlknKdeOR0) 上图为开启插件状态。 ![image](https://private-user-images.githubusercontent.com/71172482/297130128-edf980df-c4bb-4bfa-bc50-4623e5445a29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjAxNjgsIm5iZiI6MTcwNTQ1OTg2OCwicGF0aCI6Ii83MTE3MjQ4Mi8yOTcxMzAxMjgtZWRmOTgwZGYtYzRiYi00YmZhLWJjNTAtNDYyM2U1NDQ1YTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAyNTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOGY4ZmU1YzQyZWVkNjNlMjMyOWM4NzlhYWMyZjdhNWEzNzQyYzlhNGVhMDQyMjVlOGI5NzMzNjQ2YmJjODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E_YLNwmFVMgHAii439eIlyFA7B4CbSxEb8IFCbxtYfE) 上图为关闭插件状态。
> > 打开 的笔记 中callout数量为5个。
> 
> 请试试 关闭所有的插件和主题，只使用官方主题和knote，看下是否还卡顿；
![37b5456cb1e404612f746a4ee7f2473e](https://github.com/suka233/siyuan-knote/assets/71172482/02e4f0c9-98e4-4d5b-a4ea-32da2661136e)
上图为所有插件全部关闭，只开启了KNote插件的情况
![e99b660581cb00670ee737e7df57109d](https://github.com/suka233/siyuan-knote/assets/71172482/745e0517-03b1-4e84-834a-554fa911dc25)

上图为所有插件全部关闭(包括KNote)

**Comment by suka233** [comment]
> > > 此BUG，目前来看，依然存在。
> > > 当前已处于思源版本最新，插件版本最新。 ![image](https://private-user-images.githubusercontent.com/71172482/297129896-99eef35b-a42a-4791-9971-03746623b232.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjAxNjgsIm5iZiI6MTcwNTQ1OTg2OCwicGF0aCI6Ii83MTE3MjQ4Mi8yOTcxMjk4OTYtOTllZWYzNWItYTQyYS00NzkxLTk5NzEtMDM3NDY2MjNiMjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAyNTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYTk3MGYzNWJkNWRlZWUwNWM5ZmEzMWVmYWQ5NjZmY2JjOTRjYTA2NzZhMTM1ZWNhYWRiM2QzMDQwYjM2MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1sOFtddSEuW382oPphE95XXYJZJ_gqoTeBlknKdeOR0) 上图为开启插件状态。 ![image](https://private-user-images.githubusercontent.com/71172482/297130128-edf980df-c4bb-4bfa-bc50-4623e5445a29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjAxNjgsIm5iZiI6MTcwNTQ1OTg2OCwicGF0aCI6Ii83MTE3MjQ4Mi8yOTcxMzAxMjgtZWRmOTgwZGYtYzRiYi00YmZhLWJjNTAtNDYyM2U1NDQ1YTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAyNTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOGY4ZmU1YzQyZWVkNjNlMjMyOWM4NzlhYWMyZjdhNWEzNzQyYzlhNGVhMDQyMjVlOGI5NzMzNjQ2YmJjODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E_YLNwmFVMgHAii439eIlyFA7B4CbSxEb8IFCbxtYfE) 上图为关闭插件状态。
> > > 打开 的笔记 中callout数量为5个。
> > 
> > 
> > 请试试 关闭所有的插件和主题，只使用官方主题和knote，看下是否还卡顿；
> > ![37b5456cb1e404612f746a4ee7f2473e](https://private-user-images.githubusercontent.com/71172482/298605118-02e4f0c9-98e4-4d5b-a4ea-32da2661136e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjExODAsIm5iZiI6MTcwNjA2MDg4MCwicGF0aCI6Ii83MTE3MjQ4Mi8yOTg2MDUxMTgtMDJlNGYwYzktOThlNC00ZDViLWE0ZWEtMzJkYTI2NjExMzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAxNDgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMGNmMzBhMWU1NDRhOGE3YjFlZDkzMjdkMzViZmMxMzAwZjhkMTRkYTZhNjZhOTU0MjhhZjM4MWMwNmQ1NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AkaZwsT1zpcbi-5TM9p6nK3fsHk2Wqu0lCvU05UaLYg)
> > 上图为所有插件全部关闭，只开启了KNote插件的情况
> > ![e99b660581cb00670ee737e7df57109d](https://private-user-images.githubusercontent.com/71172482/298605221-745e0517-03b1-4e84-834a-554fa911dc25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjExODAsIm5iZiI6MTcwNjA2MDg4MCwicGF0aCI6Ii83MTE3MjQ4Mi8yOTg2MDUyMjEtNzQ1ZTA1MTctMDNiMS00ZTg0LTgzNGEtNTU0ZmE5MTFkYzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAxNDgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYWU4MTY5MDMyN2E5MmU3MTJmMGUzNWQzMjYxZGVjOTljNTA0YmI2MzBiYjcxNTcyMjE0NmMyODBkMmUzYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IATeQiqjfDa5D5GXWBAg14VRyUWQ4PcUirFiHYkOQ40)
> 
> 上图为所有插件全部关闭(包括KNote)


knote插件开启后，多了一个进程和100多的内存占用是正常的。因为knote大概的技术原理是：为了按下快捷键就能瞬间弹出全局窗口，免去加载过程，knote会在启动的时候在后台缓存一个窗口备用，这是做的用户体验优化而不得不占用的内存。
可能需要你在方便和内存之间做一个取舍了。

如果有其它问题请继续反馈
