### ISSUE TITLE
黑夜模式下，面板打开，里面什么也看不清楚哦

### ISSUE THREAD

**Issue by uulaile** [suka233/siyuan-knote#3]
黑夜模式下，面板打开，里面什么也看不清楚哦
![image](https://github.com/suka233/siyuan-knote/assets/96331996/232c02f6-a5d7-4744-9684-9b8752f11a2f)

**Comment by uulaile** [comment]
催更

**Comment by suka233** [comment]
> 催更

你让我有了上班的感觉。。！！！
不过已经更新好了：v1.3.0 ，等思源拉取我的仓库后，在集市更新即可，等不及的话也可以在release中手动下载最新的package包，解压到knote目录下就行
