### ISSUE TITLE
可以考虑下使用新增的/api/block/appendDailyNoteBlock接口

### ISSUE THREAD

**Issue by zxhd863943427** [suka233/siyuan-knote#5]
接口详情参见：https://github.com/siyuan-note/siyuan/issues/10368

**Comment by suka233** [comment]
方便确实方便了很多，使用这个api的话确实会更无感，但是感觉多了一些危险性。
用户无感知的情况下就这样创建文档的话，多端使用大概率会造成冲突。

设想一个场景（假设knote已经用上了这个api）：
比如今天我并没有手动新建日记文档，然后我在手机端使用knote记录了，然后过了两分钟，我在电脑上也用knote记录了一条，这个时候，两端一同步就会造成文档冲突，因为手机端使用这个api自动创建日记文档和电脑端自动创建的日记文档其实是不同id的文档。

**Comment by zxhd863943427** [comment]
嗯，确实会多一个这个风险……但是之前的方案似乎没没法避免这种情况吧。或许可以在创建之前先自动同步一下？

另外多端对于单文档编辑才是冲突，这只是产生同名不同id的文档，可以比较轻松的转移笔记内容。这个角度来说，之前的方案风险更大一点。

**Comment by suka233** [comment]
搞定

**Comment by zxhd863943427** [comment]
不错，over
