### ISSUE TITLE
Show Only Selected Elements in the Menu

### ISSUE THREAD

**Issue by TheNomadInOrbit** [suka233/siyuan-knote#8]
When using /, you should only display the elements marked with rectangles as shown in the picture below. This is to improve the UI by eliminating unnecessary text space. Additionally, this section also requires support for English. Thanks.

![image](https://github.com/suka233/siyuan-knote/assets/36538038/3e241def-c5ac-44e3-8ae3-8e22b2da86cd)

**Comment by suka233** [comment]
fixed
