### ISSUE TITLE
摘录之后似乎会添加内容到书签

### ISSUE THREAD

**Issue by TangQi001** [suka233/siyuan-knote#9]
![image](https://github.com/suka233/siyuan-knote/assets/67812425/ce9d5f13-2c2c-4e2f-bf23-0df6482aaa0c)

这样子会不会使得书签的使用不方便了
![image](https://github.com/suka233/siyuan-knote/assets/67812425/8347f263-c806-400e-b01d-e2fb8a626f35)

**Comment by suka233** [comment]
我试了试，添加书签是设计之外的东西。

这个属性“ki-bookmark”的作用是：当你在闪卡复习界面，复习比较长的闪卡的时候（一般是在闪卡界面阅读一篇文章），自动存储当前的滚动位置，以便下次复习这张闪卡的时候自动跳转到该位置，理论上来说不会污染任何笔记内容。

所以，这个可能是思源的bug，错误的把自定义属性添加到思源的书签当中了。
也有可能是特性，把自定义属性值为bookmark结尾的块自动加入到书签中。以下是我的复现步骤：
随便给一个块添加一个bookmark结尾的自定义属性，属性值也随便填写，然后就可以看到这个块被加入到书签中了：
![image](https://github.com/suka233/siyuan-knote/assets/43712875/4f194032-b41b-4767-a5ac-4b44339d405b)

最后 ，可以去siyuan的仓库提一下issue问一问，如果是bug，估计下周就修复了。

**Comment by TangQi001** [comment]
![image](https://github.com/suka233/siyuan-knote/assets/67812425/8a83cca3-f526-4585-bdc7-95a1634baf86)
D大给回复了，这个插件的属性名要不要换一下更好一些
![Suggestion](https://github.com/suka233/siyuan-knote/assets/67812425/be9e3af1-9747-4ac2-a20f-635a8f299621)

**Comment by suka233** [comment]
> ![image](https://private-user-images.githubusercontent.com/67812425/325281944-8a83cca3-f526-4585-bdc7-95a1634baf86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzQwMDUsIm5iZiI6MTcxNDM3MzcwNSwicGF0aCI6Ii82NzgxMjQyNS8zMjUyODE5NDQtOGE4M2NjYTMtZjUyNi00NTg1LWJkYzctOTVhMTYzNGJhZjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA2NTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NzZiMjU3NTRjNGYwNDQ0NzE4NDJkMjI1OWY2MTgxMjgwMzQ1YWQ1N2Q2MTkwNTE4NWU2NjNlZTdiOWU2NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UtkaWA8Y2poFvwewfqCtapEMXioD5vxiUr8z-AwtN1o) D大给回复了，这个插件的属性名要不要换一下更好一些 ![Suggestion](https://private-user-images.githubusercontent.com/67812425/325282144-be9e3af1-9747-4ac2-a20f-635a8f299621.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzQwMDUsIm5iZiI6MTcxNDM3MzcwNSwicGF0aCI6Ii82NzgxMjQyNS8zMjUyODIxNDQtYmU5ZTNhZjEtOTc0Ny00YWMyLWEyMGYtNjM1YThmMjk5NjIxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA2NTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMDJjYmYyZjY0YTNjZDIzNDAzYTEwODhhY2I0OWY2NDFmZDY4MjhlNWE2NmY4Mjg4MjNlYzYwODYwZTY2NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NqhOTsYZuD4EpSGtB7kNsB3Asw6sUG0SvLOEGDoTfUY) [ ![Suggestion](https://private-user-images.githubusercontent.com/67812425/325282144-be9e3af1-9747-4ac2-a20f-635a8f299621.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzQwMDUsIm5iZiI6MTcxNDM3MzcwNSwicGF0aCI6Ii82NzgxMjQyNS8zMjUyODIxNDQtYmU5ZTNhZjEtOTc0Ny00YWMyLWEyMGYtNjM1YThmMjk5NjIxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA2NTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMDJjYmYyZjY0YTNjZDIzNDAzYTEwODhhY2I0OWY2NDFmZDY4MjhlNWE2NmY4Mjg4MjNlYzYwODYwZTY2NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NqhOTsYZuD4EpSGtB7kNsB3Asw6sUG0SvLOEGDoTfUY) ](https://private-user-images.githubusercontent.com/67812425/325282144-be9e3af1-9747-4ac2-a20f-635a8f299621.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzQwMDUsIm5iZiI6MTcxNDM3MzcwNSwicGF0aCI6Ii82NzgxMjQyNS8zMjUyODIxNDQtYmU5ZTNhZjEtOTc0Ny00YWMyLWEyMGYtNjM1YThmMjk5NjIxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA2NTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMDJjYmYyZjY0YTNjZDIzNDAzYTEwODhhY2I0OWY2NDFmZDY4MjhlNWE2NmY4Mjg4MjNlYzYwODYwZTY2NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NqhOTsYZuD4EpSGtB7kNsB3Asw6sUG0SvLOEGDoTfUY) [ ](https://private-user-images.githubusercontent.com/67812425/325282144-be9e3af1-9747-4ac2-a20f-635a8f299621.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzQwMDUsIm5iZiI6MTcxNDM3MzcwNSwicGF0aCI6Ii82NzgxMjQyNS8zMjUyODIxNDQtYmU5ZTNhZjEtOTc0Ny00YWMyLWEyMGYtNjM1YThmMjk5NjIxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA2NTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMDJjYmYyZjY0YTNjZDIzNDAzYTEwODhhY2I0OWY2NDFmZDY4MjhlNWE2NmY4Mjg4MjNlYzYwODYwZTY2NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NqhOTsYZuD4EpSGtB7kNsB3Asw6sUG0SvLOEGDoTfUY)

如果这不是特性的话，我更倾向于给思源提issue，让思源来改，毕竟保不齐之后另一个作者的插件也会在不知情的前提下采用包含“bookmark”这个字符串的属性名。
现阶段的观察是，包含有bookmark属性的块会自动添加到名称为空白的书签下（如下图绿框所示），其实只要折叠忽略掉，也没啥大问题。。至少我从来没注意过。
![image](https://github.com/suka233/siyuan-knote/assets/43712875/037911bb-5260-4db5-8d99-7a81fc2bba19)
